name: Validate

on:
  push:
  pull_request:

jobs:
  macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Validate plugin and installer
        run: ./tests/test-static.sh
